### ISSUE TITLE
关于ESP8266_IRC项目中HXD019驱动的问题

### ISSUE THREAD

**Issue by sidianneng** [IoTServ/McuNode-server#3]
首先，不好意思，本来这个问题应该提到ESP8266_IRC项目，但是由于该项目没有开启issue。所以只能暂时提到这里。
具体问题：
我在将HXD019的驱动移植到我自己的工程中后，相关基础控制逻辑可以正常工作，通过hxd019_noarc_write_test也可以正常发送红外信号。目前碰到的问题是在尝试控制HXD019学习新的红外信号后并发出，我发现其可以正常获取到相关的I2C数据，并且其校验也没有问题。但是我按照注释要求进行数据打包并发回给HXD019后，其并没有发出任何红外信号。

这里想了解下你当时是怎么测试这个功能的。

热切期盼你的回复。

**Comment by sidianneng** [comment]
经过进一步调试发现，当学习数据长度为110时，0x30+0x00+(109bytes data, delete the first byte)+checksum这种情况下是不能正常工作的。
而学习长度为230时，0x30+0x00+(229bytes data, delete the first byte)+checksum，这种情况下是可以正常工作的。
暂时不清楚为什么110字节的方法不行，可能跟我用的芯片有关系(我用的HXD019D-ML)。

**Comment by IoTServ** [comment]
不好意思，当初他们给的资料太少我也没有调通

**Comment by IoTServ** [comment]
我好像最后使用PWM还是啥的采集波形了

**Comment by sidianneng** [comment]
这样啊，既然我给调通了，是否需要我给你PR可以正常学习的代码，这样也能方便后来人~

**Comment by IoTServ** [comment]
> 这样啊，既然我给调通了，是否需要我给你PR可以正常学习的代码，这样也能方便后来人~

好啊，做个记录那挺好，你提吧

**Comment by sidianneng** [comment]
PR提交好了，辛苦你帮忙审查合并下~

**Comment by IoTServ** [comment]
> PR提交好了，辛苦你帮忙审查合并下~

已经合并好了，感谢你的提交！
